Mess Extra management System/devathon/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('vendor/', include('vendor.urls', namespace='vendor')),
    
   path('student/',include('student.urls',namespace='student')),

   
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    
]

Mess Extra management System/student/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [

    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
]

Mess Extra management System/student/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import userlist, order, pending, details
app_name = 'student'

urlpatterns = [
    path('dashboard/', userlist, name='dashboard'),
    path('placeorder/', order, name='placeorder'),
    path('pending/', pending, name='pending'),
    path('pending/<int:transid>', details, name="details"),


]

Mess Extra management System/student/accounts/models.py
from django.db import models

# Create your models here.

Mess Extra management System/student/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pass_code = models.CharField(max_length=4, default="")

    def save(self):
        super().save()

    def __str__(self):
        return self.user.username

Mess Extra management System/student/accounts/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.admin import User
from django.core.exceptions import ObjectDoesNotExist


class UserRegForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.RegexField(
        regex="^[1-9][0-9]{5}$", error_messages={'invalid': 'Enter Proper Username'})
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput(), validators=[
                                RegexValidator('^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,}$')], error_messages={'invalid': "Enter valid password"})
    password2 = forms.CharField(widget=forms.PasswordInput(),)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = None
        try:
            try:
                user = User.objects.get(username=username)
            except ObjectDoesNotExist as e:
                pass
            except Exception as e:
                raise e
            if not user:
                pass
            else:
                # print("jris")
                raise forms.ValidationError("Username Already Exists")
        except Exception as e:
            raise e
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = None
        try:
            try:
                user = User.objects.get(email=email)
            except ObjectDoesNotExist as e:
                pass
            except Exception as e:
                raise e
            if not user:
                pass
            else:
                raise forms.ValidationError(
                    "User with the email ID Already Exists")
        except Exception as e:
            raise forms.ValidationError(
                "User with the email ID Already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError("Passwords doesn't Match")
        return password2

Mess Extra management System/student/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from student.models import Student
from .forms import UserRegForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.admin import User


def user_login(request):
    if request.user.is_authenticated:
        try:
            Student.objects.get(user=request.user)
            return redirect('student:dashboard')
        except:
            return redirect('vendor:dashboard')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        # print(user.password)
        if user is not None:
            if user.is_active:
                login(request, user)
                try:
                    Student.objects.get(user=user)
                    return redirect('student:dashboard')
                except:
                    return redirect('vendor:dashboard')
            else:
                messages.error(request, "Username not Active")
                return redirect('accounts:login')
        else:
            messages.error(request, "Invalid Credentials")
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect("accounts:login")


def regUser(form):
    user = User.objects.create_user(username=form['username'], first_name=form['first_name'],
                                    last_name=form['last_name'], email=form['email'], password=form['password1'])
    user.save()
    student = Student(user=user, pass_code="-1")
    student.save()


def user_register(request):
    if request.user.is_authenticated:
        try:
            Student.objects.get(user=request.user)
            return redirect('student:dashboard')
        except:
            return redirect('vendor:dashboard')
    if request.method == "POST":
        form = UserRegForm(request.POST)
        if form.is_valid():
            # print(form['username'])
            # print(form.cleaned_data)
            regUser(form.cleaned_data)
            messages.success(request, "Registration Successful")
            return redirect('accounts:login')
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)
            return redirect("accounts:register")
    else:
        return render(request, 'accounts/register.html')

Mess Extra management System/student/views.py
from devathon.settings import EMAIL_HOST, EMAIL_HOST_PASSWORD, EMAIL_HOST_USER, EMAIL_PORT
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404, HttpResponse
from django.views.generic import ListView
from student.models import Student
from django.shortcuts import render, redirect
from vendor.models import ExtraItems, Token, Transaction
from django.shortcuts import get_object_or_404
# Create your views here.
from vendor.models import Token
from django.contrib import messages
import random
import smtplib

from django.contrib.auth import get_user_model

User = get_user_model()


"""
def check(user):
    try:
        print('in try')
        S = get_object_or_404(Student,user=user)
        if S:
            return True
    except:
        print('in expect')
        return False

"""
"""
def check(user):
    if Student.objects.get(user=user):
        return True
    else:
        return False

"""


def check(user):
    return Student.objects.filter(user=user).exists()


@login_required
@user_passes_test(check)
def userlist(request):
    tok_list = Token.objects.filter(
        trans_id__reg_id__user__username=request.user.username).filter(trans_id__status='A')
    # print(tok_list)
    due_total = 0
    for tok in tok_list:
        due_total += ((int(tok.item_name.item_cost))*(int(tok.quantity)))

    return render(request, 'student/dashboard.html', {'token_list': tok_list, 'due_total': due_total})


"""
class UserToken(ListView):
    model = Token
    template_name = 'student/dashboard.html'

    def get_queryset(self):
        try:
            self.token_user = Student.objects.prefetch_related('token').get(username__iexact=)
        except User.DoesNotExist:
            print("jkdb")
            raise Http404
        else:
            return self.post_user.token.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['tokenuser'] = self.token_user
        return context
"""


def createTranId():
    transId = random.randint(100000000, 999999999)
    count = 20
    while count > 0:
        if Transaction.objects.filter(trans_id=transId).exists():
            count = count - 1
            transId = random.randint(100000000, 999999999)
        else:
            break
    if count == 0:
        return HttpResponse('Could not create transaction ID Try again after a while', status=405)
    return transId


def generate_otp():
    return random.randint(100000, 999999)


def sendEmail(to, transid, otp):
    print(to)
    try:
        server = smtplib.SMTP(EMAIL_HOST,EMAIL_PORT)
        server.ehlo()
        server.starttls()
        print(server.login(EMAIL_HOST_USER,EMAIL_HOST_PASSWORD))
        server.sendmail(EMAIL_HOST_USER, to,
                        f'Thanks for odering with us. Your OTP for transaction {transid} is {otp}.')
        server.close()
        return True
    except Exception as e:
        return False


@login_required
@user_passes_test(check)
def order(request):
    if Transaction.objects.filter(reg_id__user=request.user, status='P').count() >= 10:
        flag = True
        return render(request, 'student/order.html', {'flag': flag})
    if request.method == "POST":
        try:
            student = Student.objects.get(user=request.user)
            quants = []
            # print(student)
            for item in request.POST:
                if item != 'csrfmiddlewaretoken':
                    try:
                        found = get_object_or_404(
                            ExtraItems, item_name=item)
                        quantity = int(request.POST[item])
                        if quantity > 0:
                            quants.append((quantity, found))
                            # print(quantity)
                    except:
                        pass
            if len(quants):
                transid = createTranId()
                otp = generate_otp()
                # print(transid, otp)
                transaction = Transaction(
                    trans_id=transid, reg_id=student, otp=otp)
                transaction.save()
                for item in quants:
                    # print(item)
                    token = Token.objects.create(
                        trans_id=transaction, item_name=item[1], quantity=item[0])
                    token.save()
                # print(request.user.email)
                if sendEmail(request.user.email, transid, otp):
                    # print("kriabsf")
                    messages.success(request, "Order Placed successfully")
                return redirect('student:placeorder')
            else:
                messages.error(request, "Don't fill fake forms")
                return redirect('student:placeorder')
        except:
            messages.error(request, "Something went wrong")
            return redirect('student:placeorder')
    extraItems = ExtraItems.objects.all()
    content = {
        "extraItems": extraItems,
    }
    return render(request, 'student/order.html', content)


@login_required
@user_passes_test(check)
def pending(request):
    transaction = Transaction.objects.filter(
        reg_id__user=request.user, status='P')
    # print(transaction)
    return render(request, 'student/pending.html', {'transaction': transaction})


@login_required
@user_passes_test(check)
def details(request, transid):
    transaction = get_object_or_404(Transaction, trans_id=transid)
    tok_list = Token.objects.filter(trans_id=transaction)
    # print(tok_list)
    # print(transaction)
    return render(request, 'student/details.html', {'transaction': transaction, 'token_list': tok_list})

Mess Extra management System/templates/student/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Dashboard{% endblock %}

{% block body %}


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
          <a class="navbar-brand" href="#">Mess Service</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:placeorder'%}">Place Order </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:pending'%}">Pending Transactions </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
</nav>
<div class="container">
    <div class="jumbotron" style="height: 100px;padding-top: 2rem;">
        <h1 ><strong>All Transactions</strong> </h1>
    </div>
<!-- 
      <div class="container mb-4">
        <div class="row">
          
          <div class="col-3">
            Student Roll
          </div>
          <div class="col-2">
            Item
          </div>
          <div class="col-2 text-center">
            Quantity
          </div>
          <div class="col-2 text-center">
            Amount
          </div>
          <div class="col-3 text-right pr-4">
            Date - Time
          </div>
        </div>
      </div> -->


        <!-- <div class="breadcrumb">
            <div class="container">
                <div class="row">
                  <div class="col-3 px-0">
                    {{ tok.reg_id.user.username }}
                  </div>
                  <div class="col-2 px-0">
                    {{ tok.item_name }}
                  </div>
                  <div class="col-2 text-center">
                    {{ tok.quantity }}
                  </div>
                  <div class="col-2 text-center">
                   {{ tok.item_name.item_cost }}
                  </div>
                  <div class="col-3 text-right text-wrap">
                    {{ tok.date }}
                  </div>
                </div>
              </div>
        </div> -->
        <div>

        
        <h2>
          <span class="badge badge-warning badge-lg">Extra Dues : ₹ {{ due_total }}</span>
        </h2>
      </div>
      {% if messages %}
                <div id="message">
                {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}
        <table class="table">
          <thead>
            <tr>

              <th scope="col">Item name</th>
              <th scope="col">Cost per item</th>
              <th scope="col">Quantity</th>
              <th scope="col"> Date </th>
            </tr>
          </thead>
          
      {% for tok in token_list %}          
          <tbody>
            <tr>
              <td>{{ tok.item_name }}</td>
              <td>{{ tok.item_name.item_cost }}</td>
              <td>{{ tok.quantity }}</td>
              <td>{{ tok.date }}</td>
            </tr>
          </tbody>
        
        {% endfor %}
      </table>
      {% endblock %}

Mess Extra management System/templates/student/details.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Dashboard{% endblock %}

{% block body %}


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
          <a class="navbar-brand" href="#">Mess Service</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:dashboard'%}">Dashboard </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:placeorder'%}">Place Order </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:pending'%}">Pending Transactions </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
</nav>
<div class="container">
    <div class="jumbotron" style="height: 100px;padding-top: 2rem;">
        <h1>Transaction : {{transaction.trans_id}} OTP : {{transaction.otp}}</h1>
    </div>
<!-- 
      <div class="container mb-4">
        <div class="row">
          
          <div class="col-3">
            Student Roll
          </div>
          <div class="col-2">
            Item
          </div>
          <div class="col-2 text-center">
            Quantity
          </div>
          <div class="col-2 text-center">
            Amount
          </div>
          <div class="col-3 text-right pr-4">
            Date - Time
          </div>
        </div>
      </div> -->


        <!-- <div class="breadcrumb">
            <div class="container">
                <div class="row">
                  <div class="col-3 px-0">
                    {{ tok.reg_id.user.username }}
                  </div>
                  <div class="col-2 px-0">
                    {{ tok.item_name }}
                  </div>
                  <div class="col-2 text-center">
                    {{ tok.quantity }}
                  </div>
                  <div class="col-2 text-center">
                   {{ tok.item_name.item_cost }}
                  </div>
                  <div class="col-3 text-right text-wrap">
                    {{ tok.date }}
                  </div>
                </div>
              </div>
        </div> -->
        
      {% if messages %}
                <div id="message">
                {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Item name</th>
              <th scope="col">Cost per item</th>
              <th scope="col">Quantity</th>
              <th scope="col"> Date </th>
            </tr>
          </thead>
          
      {% for tok in token_list %}          
          <tbody>
            <tr>
              <td>{{ tok.item_name }}</td>
              <td>{{ tok.item_name.item_cost }}</td>
              <td>{{ tok.quantity }}</td>
              <td>{{ tok.date }}</td>
            </tr>
          </tbody>
        
        {% endfor %}
      </table>
      {% endblock %}

Mess Extra management System/templates/student/order.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Orders{% endblock %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <a class="navbar-brand" href="#">Mess Service</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:dashboard'%}">Dashboard </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:pending'%}">Pending Transactions </a>
              </li>
            <li class=" nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% if flag %}
     <div class="jumbotron">
        <h1 class="display-4"><strong>You have exceeded total no of pending transactions : 3</strong> </h1>
    </div>
    {% else %}
    <div class="jumbotron">
        <h1 class="display-4"><strong>Place Order</strong> </h1>
    </div>

    <form class="form-signin" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="container">
            {% if messages %}
                <div id="message">
                {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}
                {% for extraItem in extraItems %}
                <div class="row m-2 border-bottom">
                    <div class="col-3"><label>{{extraItem.item_name}} </label></div>
                    <div class="col-1"><label class="badge badge-secondary p-2">Rs. {{extraItem.item_cost}} </label>
                    </div>
                    <div class="col-4">
                        <label>Q : </label>
                        <input class="mr-2" type="number" name="{{extraItem.item_name}}" min="0" max="5" value=0 />
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary">
        </div>
    </form>
    {% endif %}
</div>



{% endblock %}

Mess Extra management System/templates/student/pending.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Pending Transactions{% endblock %}

{% block body %}


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <a class="navbar-brand" href="#">Mess Service</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:dashboard'%}">Dashboard </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'student:placeorder'%}">Place Order </a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="jumbotron" style="height: 100px;padding-top: 2rem;">
        <h1><strong>Pending Transactions</strong> </h1>
    </div>
    <!-- 
      <div class="container mb-4">
        <div class="row">
          
          <div class="col-3">
            Student Roll
          </div>
          <div class="col-2">
            Item
          </div>
          <div class="col-2 text-center">
            Quantity
          </div>
          <div class="col-2 text-center">
            Amount
          </div>
          <div class="col-3 text-right pr-4">
            Date - Time
          </div>
        </div>
      </div> -->


    <!-- <div class="breadcrumb">
            <div class="container">
                <div class="row">
                  <div class="col-3 px-0">
                    {{ tok.reg_id.user.username }}
                  </div>
                  <div class="col-2 px-0">
                    {{ tok.item_name }}
                  </div>
                  <div class="col-2 text-center">
                    {{ tok.quantity }}
                  </div>
                  <div class="col-2 text-center">
                   {{ tok.item_name.item_cost }}
                  </div>
                  <div class="col-3 text-right text-wrap">
                    {{ tok.date }}
                  </div>
                </div>
              </div>
        </div> -->
      
      {% if messages %}
                <div id="message">
                {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Transaction ID</th>
                <th scope="col">OTP</th>
                <th scope="col"> Details</th>
            </tr>
        </thead>

        {% for tok in transaction %}
        <tbody>
            <tr>
                <td>{{ tok.trans_id }}</td>
                <td>{{ tok.otp }}</td>
                <td><a type="submit" class="btn btn-secondary" href="{% url 'student:details' tok.trans_id %}">View</a>
                </td>
            </tr>
        </tbody>

        {% endfor %}
    </table>
    {% endblock %}